// <auto-generated />
using System;
using GestionAbsence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GestionAbsence.Migrations
{
    [DbContext(typeof(GestionAbsenceDbContext))]
    [Migration("20220308110245_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("GestionAbsence.Absence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsJournee")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMatin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Absences");
                });

            modelBuilder.Entity("GestionAbsence.Justificatif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AbsenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Chemin")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RetardId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AbsenceId");

                    b.HasIndex("RetardId");

                    b.ToTable("Justificatits");
                });

            modelBuilder.Entity("GestionAbsence.Retard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duree")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMatin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Retards");
                });

            modelBuilder.Entity("GestionAbsence.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Libelle")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GestionAbsence.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GestionAbsence.Absence", b =>
                {
                    b.HasOne("GestionAbsence.User", null)
                        .WithMany("Absences")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("GestionAbsence.Justificatif", b =>
                {
                    b.HasOne("GestionAbsence.Absence", null)
                        .WithMany("Justificatifs")
                        .HasForeignKey("AbsenceId");

                    b.HasOne("GestionAbsence.Retard", null)
                        .WithMany("Justificatifs")
                        .HasForeignKey("RetardId");
                });

            modelBuilder.Entity("GestionAbsence.Retard", b =>
                {
                    b.HasOne("GestionAbsence.User", null)
                        .WithMany("Retards")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("GestionAbsence.User", b =>
                {
                    b.HasOne("GestionAbsence.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GestionAbsence.Absence", b =>
                {
                    b.Navigation("Justificatifs");
                });

            modelBuilder.Entity("GestionAbsence.Retard", b =>
                {
                    b.Navigation("Justificatifs");
                });

            modelBuilder.Entity("GestionAbsence.User", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("Retards");
                });
#pragma warning restore 612, 618
        }
    }
}
